version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: jawscontainer
    environment:
      POSTGRES_DB: jaws
      POSTGRES_USER: postres
      POSTGRES_PASSWORD: postres
    ports:
      - "5431:5432"
    restart: always